global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "nps-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]   # change to "localhost:8000" if running locally without compose
